---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 48.1.1
  install:
    createNamespace: true
  interval: 1h0m0s
  targetNamespace: monitoring
  values:
    grafana:
      adminPassword: admin@123
    kubeStateMetrics:
      enabled: true
    prometheus:
      prometheusSpec:
        serviceMonitorSelector:
          matchLabels:
            release: prometheus
        serviceMonitorSelectorNilUsesHelmValues: false
