---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: dev-cluster
  interval: 1h0m0s
  path: ./flux-cluster/dev-cluster/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
