apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helmrelease
  namespace: flux-system
spec:
  interval: 10s
  chart:
    spec:
      chart: mychart
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: gitrepository
        namespace: flux-system
      reconcileStrategy: Revision
  targetNamespace: demo
  valuesFiles:
    - mychart/values.yaml