---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helmrelease
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mychart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: gitrepository
  interval: 10s
  targetNamespace: demo
  values:
    app:
      image:
        pullPolicy: Always
        repository: maheshgowdamg25/springapp
        tag: bec3a43ba6e3a98e1e35e2629a149176de05f211
      labels:
        app: myapp
      name: springapp
      port: 9000
      service:
        nodePort: 30090
        type: NodePort
    replicaCount: 3
