---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helmrelease
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mychart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: gitrepository
  interval: 10s
  targetNamespace: demo
 