apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helmrelease
  namespace: flux-system
spec:
  interval: 1m0s
  targetNamespace: demo
  chart:
    spec:
      chart: ./mychart     # This is a local path inside the repo
      sourceRef:
        kind: GitRepository
        name: gitrepository
        namespace: flux-system
      reconcileStrategy: Revision
  
